CREATE DATABASE RETAILSHOP;
USE RETAILSHOP;

CREATE TABLE CUSTOMERS(
CUSTOMERID INT PRIMARY KEY,
NAME VARCHAR(50)
);


CREATE TABLE ORDERS (
ORDERID INT ,
PRODUCT VARCHAR(50),
AMOUNT DECIMAL(10,2),
CUSTOMERID INT,
foreign key(CUSTOMERID)references CUSTOMERS(CUSTOMERID)
);


INSERT INTO CUSTOMERS values 
(1,'ROHAN CHOUAN'),
(2,'ANJALI MEHTA'),
(3,'AMIT SHARMA');

INSERT INTO ORDERS values 
(101,'LAPTOP',50000,2),
(102,'MOUSE',1500,1),
(103,'KEYBOARD',700,1);

SHOW TABLES;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

SELECT CUSTOMERS.NAME , ORDERS.PRODUCT, ORDERS.AMOUNT 
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID;

# FULL JION MEAN LEFT JION + RIGHT JION BOTH ADDED BY UNION  
SELECT CUSTOMERS.NAME , ORDERS.PRODUCT, ORDERS.AMOUNT 
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID

UNION

SELECT CUSTOMERS.NAME , ORDERS.PRODUCT, ORDERS.AMOUNT 
FROM CUSTOMERS
RIGHT JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID;
