CREATE DATABASE IF NOT EXISTS SALEDB;
USE SALEDB;
CREATE TABLE PRODUCT (
PRODUCT_ID INT auto_increment PRIMARY KEY,
PRODUCT VARCHAR(55),
CATEGORY VARCHAR(50),
AMOUNT INT(10),
SALEDATE date
);
INSERT INTO PRODUCT (PRODUCT,CATEGORY,AMOUNT,SALEDATE) VALUES
("PEN","STATIONARY",25,"2024-03-01"),
("NOTEBOOK","STATIONARY",70,"2024-03-01"),
("MOUSE","ELECTRONIC",500,"2024-03-02"),
("KEYBOARD","ELECTRONIC",1200,"2024-03-02"),
("MONITOR","ELECTRONIC",3700,"2024-03-02"),
("PEN","STATIONARY",25,"2024-03-03"),
("PENCIL","STATIONARY",5,"2024-03-04"),
("CHARGER","ELECTRONICS",300,"2024-03-04"),
("BAG","STATIONARY",1000,"2024-03-05");

SELECT * FROM PRODUCT;

# COUTN   
SELECT COUNT(*) FROM PRODUCT;

# SUM
SELECT SUM(AMOUNT) FROM PRODUCT;

# AVG 
SELECT AVG(AMOUNT) FROM PRODUCT;

# MIN MAX
SELECT MIN(AMOUNT) ,MAX(AMOUNT) FROM PRODUCT;

# GROPU BY
SELECT CATEGORY ,SUM(AMOUNT) FROM PRODUCT GROUP BY CATEGORY;

# HAVING
SELECT CATEGORY ,SUM(AMOUNT) productproduct
FROM PRODUCT
GROUP BY CATEGORY 
HAVING SUM(AMOUNT) >1000;


SELECT *
FROM PRODUCT
WHERE AMOUNT> (SELECT AVG(AMOUNT) FROM PRODUCT);